### ISSUE TITLE
The package was removed from CRAN

### ISSUE THREAD

**Issue by Generalized** [moodymudskipper/flow#126]
Dear Author,
I just noticed the package is removed from CRAN.
Do you have any plans to restore it back?

https://cran.r-project.org/web/packages/flow/index.html

The issue:
![obraz](https://user-images.githubusercontent.com/60151643/199633495-49c0e149-4e90-439e-897c-8309f0a72177.png)

**Comment by moodymudskipper** [comment]
Absolutely it will be restored.
It's been taken out because of trivial html issues meanwhile the development version is not in a good enough shaped to be shipped on CRAN as is.
I need a bit of time for some fixes and polish the doc and will push it back there.
Sorry for the inconvenience.

**Comment by moodymudskipper** [comment]
It's back on, sincere apologies for all the time off. I hope you'll enjoy the new features.
