### ISSUE TITLE
Full package doc? 

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/flow#29]
This is ambitious but I think there's a path.

* list all functions from pkg
* for each fun create a diagram (or several if too long, say chunks 15 or 20 blocks high)
* use all.names to grab all used function names in  given function, which are part of pkg, they'll be used to have hyper links to other function defs
* reproduce in rmd doc the original doc structure, borrowing title, definition (not details), and arg definitions, but adding flow diagrams, and hyperlinks to sections of other used functions.
* arguments can turn on and off sections (maybe we just want diagrams, and don't care about arg def for instance
* if we have flow_doc_rmd we can easily have flow_doc_pdf and flow_doc_html too (or even a full website! flow_website /flow down? 🤔).

flow_doc_rmd(pkg, pick= NULL, skip = NULL, sections = c("title", "description", "arguments")). 

Unexported /undocumented functions are documented in an appendix in the end in alpha order, if sections is NULL, we don't follow original doc structure, just stack functions in alpha order along with hyperlinks. 

This might be a very long doc, I hope it can stay practical.

**Comment by moodymudskipper** [comment]
It seems to me now the utility would be limited, it'd be nice indeed to dig in functions used by functions but probably not worth the effort, putting on hold

**Comment by sbalci** [comment]
Hi,

Using the parameters in Rmarkdown and inspired from: https://gist.github.com/rmoff/a043676a2f084b81a434

I have done following:

### wf_master.Rmd

```yaml
---
title: "Child test"
output: html_document
---
```

```r
{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE,message=FALSE, cache=FALSE)
```


```r
{r}
packagefunctions <- getNamespaceExports(ns = "ClinicoPath")

```



```r
{r include=FALSE}
out = NULL
for (i in 1:length(functionsClinicoPath)) {
  value.to.match <- functionsClinicoPath[i]
  out = c(out,
          knitr::knit_expand(here::here('vignettes', 'wf_child.Rmd'))
  )
  }
```

```markdown
`r paste(knitr::knit(text = out), collapse = '\n')`
```



### wf_child.Rmd

```
Workflow for {{i}}
```

```markdown
`r '{{value.to.match}}'`.
```


```r
{r echo=TRUE}
value.to.match <- '{{value.to.match}}'
myfun <- paste0('ClinicoPath::', value.to.match)
flow::flow_view(x = eval(parse(text = myfun))
                )
```

**Comment by moodymudskipper** [comment]
@sbalci can you reinstall and take a look at `flow_doc()`?

`flow_doc("pkg")` will create a "pkg. html" file in your working dir. You might want to try the argument `engine = "plantuml"` too. 

If you have remarks or feature suggestions I'll be happy to read them!

**Comment by moodymudskipper** [comment]
Closing since the feature is there, additional features and improvement go to separate issues, unlikely to be tackled before CRAN.
