### ISSUE TITLE
Fails unless the whole package is attached

### ISSUE THREAD

**Issue by Bisaloo** [moodymudskipper/flow#33]
I wanted to do a quick test using the example in the `README` but

```r
flow::flow_view(median.default)
```

fails with

> Error in flow_data(median.default, NULL, NULL, NULL, TRUE, FALSE) : 
  could not find function "flow_data"

I think it's the first time I see this kind of error so I don't know how to fix it but you might.

**Comment by moodymudskipper** [comment]
Thanks so much, good catch!
it's because in flow_view I evaluate a call to flow_data in the caller environment so it doesn't look into flow's namespace. I just added `::`.

63ecd81b340f0b85c1ecc5c84cdc271844e9b63e
