### ISSUE TITLE
flow_data not found

### ISSUE THREAD

**Issue by smingerson** [moodymudskipper/flow#44]
Great R package! I ran into a few snafus when I started playing with it.

In a fresh R session,
```r
flow::flow_run(mean(1:5))
#> Error in flow_data(base::mean.default, range = NULL, prefix = NULL, sub_fun_id = NULL, : could not find function "flow_data"
```
Kinda weird, because it looks like your files will be collated in the right order, so not sure what is going on.

This works once `library(flow)` is run.

**Comment by moodymudskipper** [comment]
seems related to https://github.com/moodymudskipper/flow/issues/33, it should be straightforward to fix

**Comment by moodymudskipper** [comment]
This is fixed by https://github.com/moodymudskipper/flow/commit/9e9094197258d1186d75fef092d530ee562e53f7

Thanks a lot for the feedback!
