### ISSUE TITLE
Pretty printing of pipes

### ISSUE THREAD

**Issue by whtns** [moodymudskipper/flow#54]
This package is really cool! I'm sure you have a lot of priorities to juggle. A small request would be to make magrittr pipes print on separate lines. Maybe solved by using styler?

**Comment by moodymudskipper** [comment]
Thanks! Good point about the pipes, I haven't yet drawn many functions that used it. 

It would make sense to use styler, i had opened this already : https://github.com/moodymudskipper/flow/issues/51 . I'm keeping this open to make sure pipes print ok once #51 is done.

**Comment by moodymudskipper** [comment]
@whtns Can you reinstall and tell me what you think ? I used *{styler}* with the default style. I also changed the default font to be monospace with the nomnoml engine, I had probems changing the font with the plantuml engine for some reason.

I think ultimately, you'll be able to use the style you want through an argument and/or options.

``` r
fun <- function() {
  cars %>%
    filter(speed > 5) %>%
    mutate(a == "a")
}
flow::flow_view(fun)
```

![](https://i.imgur.com/xTWuHNV.png)

<sup>Created on 2020-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by whtns** [comment]
Wow, quick turnaround. Not familiar with the optional styles in styler but default works great for me!

**Comment by moodymudskipper** [comment]
great! I'll close this then, and will keep the linked issue open until i'm happy enough with the solution. Thanks for the issue.
