### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by jeffreyCarlLong** [moodymudskipper/flow#59]
Any idea what's going on here?

```
> install_github("moodymudskipper/flow")
Error: Failed to install 'flow' from GitHub:
  JSON: EXPECTED value GOT N
```

**Comment by moodymudskipper** [comment]
I could not reproduce it. Can you try again from a clean session and copy here the output of `sessionInfo()`?

**Comment by jeffreyCarlLong** [comment]
I can't reproduce it either. It's working now. Sorry for troubling you. Looking forward to using flow!
