### ISSUE TITLE
Flow charts that are too long are cut off in PlantUML Engine

### ISSUE THREAD

**Issue by Sheksta** [moodymudskipper/flow#69]
Hey, thanks for the promising package. I've found it very useful for understanding 1000's of lines of someone else's code for my thesis project. 

_Issue:_ I've noticed that while the PlantUML engine has been good at providing flowcharts of greater detail, the output is cut off at the bottom of the figure breaches **4096px** in height. If you use nomnoml engine the output height is adjusted to include the whole flowchart to be 9035px.

Here is an example function that will cause this issue if you try and make a flowchart of it from the plantUML engine:
[a_very_long_function.txt](https://github.com/moodymudskipper/flow/files/6410712/a_very_long_function.txt).

**Comment by moodymudskipper** [comment]
Hi and thanks!
I know the issue and wish I could help, but these are limitations of nomnoml and plantuml.
In the past I had provided a feature to split the chart for these cases but it was clunky so I removed it.
I hope I'll find a good way to address this at some point.
