### ISSUE TITLE
Add urls to DESCRIPTION so people can find the GitHub repo from CRAN

### ISSUE THREAD

**Issue by lorenzwalthert** [moodymudskipper/flow#74]
Most package have `URL:` and `BugReports:` e.g. [{styler}](https://github.com/r-lib/styler/blob/master/DESCRIPTION#L17-L18).

**Comment by moodymudskipper** [comment]
Good point thanks!

**Comment by lorenzwalthert** [comment]
BTW great to see that {styler} is used in your packages. 🎉

**Comment by moodymudskipper** [comment]
It's a great package and helped a lot in {flow} !

**Comment by moodymudskipper** [comment]
closed by 0a4482334d857d6544805acbd370e9fcaabee2a1
