### ISSUE TITLE
Focus on particular variable

### ISSUE THREAD

**Issue by jpkrooney** [moodymudskipper/flow#79]
Hi. Great package, thanks for making it.

Is it possible to name a variable and make a flow diagram of where this variable is sent as arguments in sub-functions etc? I'm asking because I'm looking at someone else complex code, and I wish to change something such that a variable is not created (to use a faster alternative method). But this means changes everywhere downstream that the variable is used. It would be really useful to be able to do something like `flow_view(function, varname, out = "file.png")`, and get a flow diagram of where this variable is passed.
Many thanks!

**Comment by jpkrooney** [comment]
Oh that would be a neat feature!

**Comment by moodymudskipper** [comment]
This can be closed now since `flow_view_vars()` is included in latest CRAN version
